name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: Check formatting
      run: nix-shell -p haskellPackages.ormolu --run "find app/ -type f | xargs -n1 ormolu --mode check"
    - name: Build
      run: nix-build
